### ISSUE TITLE
infinite recursion in moveToNextView (hotkeys.js)

### ISSUE THREAD

**Issue by joefutrelle** [LouisK130/Manual-Classify#14]
To reproduce:

- open a bin that has no annotations yet
- type "n"

Then there will be a pause where the app is frozen, followed by a "maximum stack size exceeded" in the js console, on the fn `moveToNextView` in `hotkeys.js` (which calls itself)

Tested in Firefox and Chrome

**Comment by joefutrelle** [comment]
Here's the full stacktrace

```
Uncaught RangeError: Maximum call stack size exceeded
    at Array.sort (native)
    at getTargetsInCategory (http://oneeyedjack.whoi.edu/static/javascript/utils.js:192:10)
    at reloadTargets (http://oneeyedjack.whoi.edu/static/javascript/classify.js:126:20)
    at moveToNextView (http://oneeyedjack.whoi.edu/static/javascript/hotkeys.js:102:3)
    at moveToNextView (http://oneeyedjack.whoi.edu/static/javascript/hotkeys.js:104:4)
    at moveToNextView (http://oneeyedjack.whoi.edu/static/javascript/hotkeys.js:104:4)
    at moveToNextView (http://oneeyedjack.whoi.edu/static/javascript/hotkeys.js:104:4)
    at moveToNextView (http://oneeyedjack.whoi.edu/static/javascript/hotkeys.js:104:4)
    at moveToNextView (http://oneeyedjack.whoi.edu/static/javascript/hotkeys.js:104:4)
    at moveToNextView (http://oneeyedjack.whoi.edu/static/javascript/hotkeys.js:104:4)
```

**Comment by LouisK130** [comment]
I'm on my laptop and not well-equipped to make an update and commit, but the solution is simple. Somehow a `return;` got removed from static/javascript/hotkeys.js.

See line 96 at the link below and add a return to that else block that's empty for no apparent reason.

https://github.com/LouisK130/Manual-Classify/blob/master/python/env/manualclassify/classify/static/javascript/hotkeys.js#L96

**Comment by joefutrelle** [comment]
*oops*

**Comment by LouisK130** [comment]
I think I accidentally lost it when I reworked that function a while back, not you. I guess I hadn't tested against any empty bins since then.
